SELECT A.PORTAL_LABEL, 
       B.PORTAL_NAVPATH 
FROM   PSPRSMDEFN A, 
       PSPRSMNAVINFO B 
WHERE  A.PORTAL_NAME = B.PORTAL_NAME 
       AND A.PORTAL_REFTYPE = B.PORTAL_REFTYPE 
       AND A.PORTAL_OBJNAME = B.PORTAL_OBJNAME 
       AND A.PORTAL_NAME = 'EMPLOYEE' /* <<< Enter your Portal Name Here */ 
       AND A.PORTAL_URI_SEG2 IN( 'USERMAINT', 'IB_MONITOR' ) /* <<< Enter your Component Name Here */; 